name: groovy
version: "2.5.7"
summary: test groovy build from tarball
description: |
 Test groovy build

confinement: classic
grade: devel
base: core18

apps:
  groovy:
    command: groovy-$SNAPCRAFT_PROJECT_VERSION/bin/groovy
  groovyc:
    command: groovy-$SNAPCRAFT_PROJECT_VERSION/bin/groovyc
  groovydoc:
    command: groovy-$SNAPCRAFT_PROJECT_VERSION/bin/groovydoc
  groovysh:
    command: groovy-$SNAPCRAFT_PROJECT_VERSION/bin/groovysh
  groovyConsole:
    command: groovy-$SNAPCRAFT_PROJECT_VERSION/bin/groovyConsole
  java2groovy:
    command: groovy-$SNAPCRAFT_PROJECT_VERSION/bin/java2groovy
  grape:
    command: groovy-$SNAPCRAFT_PROJECT_VERSION/bin/grape

parts:
  groovy:
    plugin: dump
    source: "https://dl.bintray.com/groovy/maven/apache-groovy-sdk-$SNAPCRAFT_PROJECT_VERSION.zip"
    source-checksum: "sha256/ea0daedf95f09ee7ff65303fd6e373c6502b2936e7616064c8abf9f74e1226b5"
    stage-packages: ["openjdk-11-jdk"]
