name: groovy
version: "2.5.7"
summary: test groovy build from tarball
description: |
 Test groovy build

confinement: classic
grade: devel
base: core18

apps:
  groovy:
    command: bin/groovy
    environment:
      STAGE_JVM: usr/lib/jvm/java-11-openjdk-amd64/bin/java
  groovyc:
    command: bin/groovyc
    environment:
      STAGE_JVM: usr/lib/jvm/java-11-openjdk-amd64/bin/java
  groovydoc:
    command: bin/groovydoc
    environment:
      STAGE_JVM: usr/lib/jvm/java-11-openjdk-amd64/bin/java
  groovysh:
    command: bin/groovysh
    environment:
      STAGE_JVM: usr/lib/jvm/java-11-openjdk-amd64/bin/java
  groovyConsole:
    command: bin/groovyConsole
    environment:
      STAGE_JVM: usr/lib/jvm/java-11-openjdk-amd64/bin/java
  java2groovy:
    command: bin/java2groovy
    environment:
      STAGE_JVM: usr/lib/jvm/java-11-openjdk-amd64/bin/java
  grape:
    command: bin/grape
    environment:
      STAGE_JVM: usr/lib/jvm/java-11-openjdk-amd64/bin/java

parts:
  groovy:
    plugin: dump
#    source: "https://dl.bintray.com/groovy/maven/apache-groovy-sdk-$SNAPCRAFT_PROJECT_VERSION.zip"
    source: "target/distributions/apache-groovy-sdk-$SNAPCRAFT_PROJECT_VERSION.zip"
    source-subdir: "groovy-$SNAPCRAFT_PROJECT_VERSION"
#    source-checksum: "sha256/ea0daedf95f09ee7ff65303fd6e373c6502b2936e7616064c8abf9f74e1226b5"
    stage-packages: ["openjdk-11-jdk"]
    override-build: |
      snapcraftctl build
      mkdir -p /etc/ssl/certs/java
      $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xmx64m -jar $SNAPCRAFT_PART_INSTALL/usr/share/ca-certificates-java/ca-certificates-java.jar -storepass changeme
